-- ============================================================
-- Rooms
-- Individual reservable rooms within a Venue's Room Matrix.
-- ============================================================

CREATE TABLE public.rooms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  venue_id UUID NOT NULL REFERENCES public.venues(id) ON DELETE CASCADE,
  number TEXT,               -- null triggers AUTO-{n} assignment on insert (see trigger below)
  name TEXT NOT NULL,
  description TEXT,
  bed_spot_count INTEGER NOT NULL,   -- max occupancy; number of individual reservable slots
  min_occupancy INTEGER NOT NULL,
  room_code TEXT,            -- free text; hotel-provided or EP-defined; null OK; not generated by platform
  lodging_type TEXT,
  bed_type TEXT,
  has_kitchen BOOLEAN NOT NULL DEFAULT false,
  location_zone TEXT,
  room_group TEXT,           -- optional grouping for EP blocking and ticket type assignment
  room_daily_rates JSONB,    -- [{ "date": "YYYY-MM-DD", "amount": 233.20 }] — check-in nights only
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()

  -- Note: no updated_at on rooms — room attributes are set at import and rarely changed
  -- Changes are tracked via event_room_config (blocking, reservation) per event
);

-- ── Indexes ──────────────────────────────────────────────────────────────────

CREATE INDEX idx_rooms_venue_id ON public.rooms(venue_id);
CREATE INDEX idx_rooms_room_group ON public.rooms(venue_id, room_group)
  WHERE room_group IS NOT NULL;

-- ── AUTO-{n} room number assignment ──────────────────────────────────────────
-- Fires on INSERT when number IS NULL.
-- Assigns AUTO-{n} where n = max existing auto-number in the same venue + 1.
-- The assigned value is stored in the number column and used everywhere
-- room numbers appear (Roommate Finder, attendance slip, hotel report).

CREATE OR REPLACE FUNCTION assign_room_auto_number()
RETURNS TRIGGER AS $$
DECLARE
  max_n INTEGER;
BEGIN
  IF NEW.number IS NULL THEN
    SELECT COALESCE(
      MAX(CAST(SUBSTRING(number FROM 6) AS INTEGER)),
      0
    ) + 1
    INTO max_n
    FROM public.rooms
    WHERE venue_id = NEW.venue_id
      AND number ~ '^AUTO-\d+$';

    NEW.number := 'AUTO-' || max_n::TEXT;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER assign_room_number_on_insert
  BEFORE INSERT ON public.rooms
  FOR EACH ROW EXECUTE FUNCTION assign_room_auto_number();

-- ── RLS ──────────────────────────────────────────────────────────────────────
-- Policies added in migration 20260101000015_rls_policies.sql.

ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
